### ISSUE TITLE
4.0 'includeAll' tag generates 2 rows in the DATABASECHANGELOG table for the same change set

### ISSUE THREAD

**Issue by szandany** [liquibase/docker#37]
Overview
Liquibase 4.0 REQUIRES to use a relative path to the changeLog.
The docker command would end up being like the following:
`docker run --rm -v <JDBC LOCAL DIR>:/liquibase/lib -v <PATH TO CHANGELOG LOCAL DIR>:/liquibase/changelog liquibase/liquibase --classpath=/liquibase/lib/<JDBC JAR FILE> --url=<JDBC URL> --changeLogFile=../liquibase/changelog/<CHANGELOG NAME ie: "changelog.xml"> --username=<USERNAME> --password=<PASSWORD> generateChangeLog`

So, the changeLog will be referenced with a relative path.  For example:
`--changeLogFile=../liquibase/changelog/<CHANGELOG NAME ie: "changelog.xml">` 

When using an includeAll tag in the changeLog, Liquibase will generate 2 rows in the DATABASECHANGELOG table for the same change set.

STR
1. Create a changeLog with includeAll tag.
2. Run update.
3. Check the corresponding rows in the DATABASECHANGELOG

ACTUAL RESULT
Here are the DOUBLE entries that get created during the update command for a single file.
`INSERT INTO mydb_dev.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('raw', 'includeAll', '../liquibase/changelog/4.460.7/LK-1055_0010.sql', NOW(), 1, '8:c113f9cc10ed2274688b871c4bdfc32a', 'sql', '', 'EXECUTED', NULL, NULL, '4.0.0', '1603317761');

INSERT INTO mydb_dev.DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, `DESCRIPTION`, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES ('raw', 'includeAll', 'changelog/4.460.7/LK-1055_0010.sql', NOW(), 3, '8:c113f9cc10ed2274688b871c4bdfc32a', 'sql', '', 'EXECUTED', NULL, NULL, '4.0.0', '1603317761');`

EXPECTED RESULT
There should be only one entry for a single changeset (file).

Notes:
Here is a related Stack Overflow case: https://stackoverflow.com/questions/64094440/liquibase-includeall-tag-generates-2-rows-in-the-databasechangelog-table-for-t

**Comment by r2liquibase** [comment]
@szandany can you check this out again? We just released a new version.

**Comment by szandany** [comment]
Hi @r2liquibase.  I Checked with all latest releases and the issue persists.

**Comment by r2liquibase** [comment]
One more check please @szandany . Thanks!

**Comment by szandany** [comment]
The issue appears to be gone with image `4.2.2`.  I'll go ahead and resolve this issue.
